### ISSUE TITLE
Wrong clone URL

### ISSUE THREAD

**Issue by sillygwailo** [hubdrop/development#15]
![screen shot 2014-03-12 at 11 12 48 pm](https://f.cloud.github.com/assets/54067/2406689/b97ce4f2-aa76-11e3-9ff9-7c959ebeed68.png)

Where did the HubDrop clone go? It's certainly not at https://github.com/project/pirate

**Comment by jonpugh** [comment]
Oh my goodness, how did that slip by??

All fixed. Thanks for the heads up!
