### ISSUE TITLE
On Set Source to GitHub, add a webhook callback to the repo.

### ISSUE THREAD

**Issue by jonpugh** [hubdrop/development#18]
When we switch source to github for a project, we should add a webhook automatically so that pushes to github go to drupal as soon as possible.

It will work now, it's just that projects where source==github will be in the jenkins queue so they won't update for 2-3 minutes.

**Comment by pirog** [comment]
Very cool!

I def noticed a similar 2-3 min delay when playing around with this on the kalatheme repo so this would be a very cool improvement.

**Comment by jonpugh** [comment]
Done. Each repo switched to GitHub should have a webhook now.

**Comment by pirog** [comment]
I see the webhooks! HUZZAH!
