### ISSUE TITLE
The default branch on the github repo doesn't match the default on the d.o repo

### ISSUE THREAD

**Issue by jonpugh** [hubdrop/development#2]
Right now it defaults to master.

**Comment by jonpugh** [comment]
calling git branch works even in a bare repo clone.  It will list all branches and \* the active one.

```
hubdrop@hubdrop:~/repos/pathauto.git$ git branch
  4.6.x-1.x
  4.7.x-1.x
  5.x-1.x
  5.x-2.x
  6.x-1.x
  6.x-2.x
* 7.x-1.x
  MAIN
  master
```

**Comment by helmo** [comment]
I also noticed this... it makes very old commits visible as a first impression on e.g. https://github.com/drupalprojects/hosting_site_git

**Comment by jonpugh** [comment]
The github repo is created before we clone the drupal.org repo, so this would have to happen on hubdrop-update-mirrors instead.  This is good, it will (i think) keep the github default branch lined up with the drupal.org default branch.

**Comment by jonpugh** [comment]
I just pushed a big refactor.  "hubdrop" is now a service.  There are commands so I can remove the hubdrop/scripts repo and keep everything in the symfony app.

**Comment by jonpugh** [comment]
All done.  Any time `\HubDrop\Bundle\Service\Project->update()` is called, the default branch is updated.
