### ISSUE TITLE
Hubdrop deleting new tags from Drupal.org repos

### ISSUE THREAD

**Issue by davereid** [hubdrop/development#24]
We experienced an issue on the views_load_more project where a maintainer was creating a new tag, creating a release node, and before the Drupal.org packaging script could run, the hubdrop sync was deleting the tag from Drupal.org. Once we removed the 'write to VCS' permission from the hubdrop user on the maintainers tab, we were able to create tags without them being deleted. It's my understanding that this is to mirror projects from Drupal.org _to_ Github, and hence data on Drupal.org is considered canonical and never altered. This does not seem to be the case.

**Comment by davereid** [comment]
Maybe this was one of those modules where the syncing was meant to go from Github to Drupal.org, but we could also just add commits to the Drupal.org repo without any issue, and there is no indication why the hubdrop user needed the 'write to VCS' access on this project, which in itself is a concerning mystery.

**Comment by jonpugh** [comment]
Terribly sorry about that! When I demoed hubdrop at the NYC meetup last month, @ericduran wanted to move that module over to github. I assumed he had the authority to direct the team to move there. 

I am going to flip the switch back to source it from drupal.org until this is sorted out.

We are now approaching the greatest challenge to this venture: communicating with the dev teams.... :cat2: :cat2: :cat2:

**Comment by jonpugh** [comment]
Switched back, as you can see at http://hubdrop.io/project/views_load_more.

The "write to VCS" is only required if you "Move the code to GitHub", which is what we did in the meetup for views_load_more.

So yes, each repo can have it's source switched between drupal.org or github.  There are a few steps required, which are listed if you click the "Move development to github" button on the hubdrop project page.  

Just to be clear, **You must be a maintainer of the drupal.org project** to be able to move your project to github.  We cannot give write access to any drupal repos but our own.

**Comment by jonpugh** [comment]
> but we could also just add commits to the Drupal.org repo without any issue

This was some strange quirk of git that I discovered when bulding this.  The tags and branches are synced as a group so when you push from one repo to the other, it will overwrite what branches or tags exist.

This is actually what prevents two-way syncing.  If it didn't erase branches & tags we could pull and push from both remotes.

**Comment by ericduran** [comment]
Yea, this was an issue on my end. 

I had recently given a couple of users commit access to that project. I should had picked a better project to play around with.

**Comment by davereid** [comment]
:punch:
