### ISSUE TITLE
Mirror sandboxes

### ISSUE THREAD

**Issue by shrop** [hubdrop/development#9]
I have some sandboxes which would be awesome to have mirrored.

**Comment by jonpugh** [comment]
I like the idea but I feel like a sandbox is the equivalent of a personal github repo.  I don't see a need to continuously sync sandboxes to github, when you could just move the code to github and end it there.

Hubdrop cycles through all mirrored repos as it updates from drupal.org, so I don't want to add to those cycles.

We could offer a command snippet that shows users how to move a sandbox to github.

I am open to having my mind changed, but it seems like a lot of work for something that you could do easily yourself.  There is nothing stopping you from using a sandbox just for the issue queue and using github for code storage.

**Comment by shrop** [comment]
Sounds good. I like the snippet idea too. Thanks for the word on this and for this awesome project.
